build: fix deploy react deps versions
Error occurred prerendering page "/blog/spaces-vs-tabs". Read more:
https://nextjs.org/docs/messages/prerender-error
Error: A React Element from an older version of React was rendered. This
is not supported. It can happen if:
- Multiple copies of the "react" package is used.
- A library pre-bundled an old copy of "react" or "react/jsx-runtime".
- A compiler tries to "inline" JSX instead of using the runtime.