fix: drop rss, og
> Error occurred prerendering page "/og". Read more:
https://nextjs.org/docs/messages/prerender-error
>
> Error: Route /og with `dynamic = "error"` couldn't be rendered
statically because it accessed `request.url`.